### ISSUE TITLE
when i open idb file, tips error

### ISSUE THREAD

**Issue by GeT1t** [igogo-x86/HexRaysPyTools#31]
```
notify_when(): Error occured while notifying object.
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\core\cache.py", line 49, in init_demangled_names
    short_name = common.demangled_name_to_c_str(short_name)
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\core\common.py", line 100, in demangled_name_to_c_str
    "implemented ({}). You can do it by yourself or create an issue".format(name))
AssertionError: Replacement of demangled string by c-string for keyword `operatorXXX` is not yetimplemented (TemplatedTestRegistrator<Suitecore_string_refkUnitTestCategory::Testoperator_equal_ReturnsTrueForEqualString<core::basic_string_ref<char>>>::Create). You can do it by yourself or create an issue
```

IDA 7.0

**Comment by igogo-x86** [comment]
You can try latest commit

**Comment by GeT1t** [comment]
not error again. Thanks
