### ISSUE TITLE
Fail to work due to deprecated IDA Python APIs with IDA 7.4 / Python 2

### ISSUE THREAD

**Issue by saidelike** [igogo-x86/HexRaysPyTools#38]
Note that I am not even talking about Python 3 here.

```
C:\Users\<user>\AppData\Roaming\Hex-Rays\IDA Pro\plugins\HexRaysPyTools.py: 'module' object has no attribute 'Choose2'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\2\ida_idaapi.py", line 619, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/<user>/AppData/Roaming/Hex-Rays/IDA Pro/plugins/HexRaysPyTools.py", line 4, in <module>
    import HexRaysPyTools.actions as actions
  File "C:/Users/<user>/AppData/Roaming/Hex-Rays/IDA Pro/plugins\HexRaysPyTools\actions.py", line 9, in <module>
    import HexRaysPyTools.forms as forms
  File "C:/Users/<user>/AppData/Roaming/Hex-Rays/IDA Pro/plugins\HexRaysPyTools\forms.py", line 7, in <module>
    class MyChoose(idaapi.Choose2):
AttributeError: 'module' object has no attribute 'Choose2'
```

See https://github.com/igogo-x86/HexRaysPyTools/blob/master/HexRaysPyTools/forms.py#L6

**Comment by igogo-x86** [comment]
You can test `feature/python3` branch. (I'm not sure there's point to keep supporting python2)

**Comment by igogo-x86** [comment]
Done by #39
