### ISSUE TITLE
Finalize button not working on IDA 7.5

### ISSUE THREAD

**Issue by shrddr** [igogo-x86/HexRaysPyTools#74]
The vftable structure does get created, but the class itself doesn't.
Output Window:
```
Traceback (most recent call last):
  File "...plugins\HexRaysPyTools\forms.py", line 93, in <lambda>
    btn_finalize.clicked.connect(lambda: self.structure_model.finalize())
  File "...plugins\HexRaysPyTools\core\temporary_structure.py", line 692, in finalize
    if self.pack():
  File "...plugins\HexRaysPyTools\core\temporary_structure.py", line 557, in pack
    cdecl = idaapi.ask_text(0x10000, '#pragma pack(push, 1)\n' + cdecl, "The following new type will be created")
TypeError: can only concatenate str (not "NoneType") to str
```

Here is the [line](https://github.com/igogo-x86/HexRaysPyTools/blob/master/HexRaysPyTools/core/temporary_structure.py#L557). Any tips how to make idaapi.print_tinfo() return something other than None? This function is listed in [IDAPython docs](https://www.hex-rays.com/products/ida/support/idapython_docs/ida_typeinf-module.html), but with no description, maybe obsolete?

**Comment by shrddr** [comment]
The problem is, `vtable_xxx` gets created with small v, but the class `xxx` expects `Vtable_xxx` with a capital V. If I change `vtable_xxx` to `Vtable_xxx` manually in Local Types window and click Finalize once more in Structure Builder, the class does get created with no error.
