### ISSUE TITLE
error when operator""

### ISSUE THREAD

**Issue by komimoe** [igogo-x86/HexRaysPyTools#89]
```Exception in ida_idp.IDP_Hooks dispatcher function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_oldfile'
Traceback (most recent call last):
  File "D:\IDA Pro 7.6.210427 (x86,x64,ARM,ARM64,PPC,PPC64,MIPS)\python\3\ida_idp.py", line 6010, in ev_oldfile
    return self.dispatcher().dispatch(ida_idaapi.NW_OPENIDB, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IDA Pro 7.6.210427 (x86,x64,ARM,ARM64,PPC,PPC64,MIPS)\python\3\ida_idp.py", line 6037, in dispatch
    cb.fun(slot, *args)
  File "D:\IDA Pro 7.6.210427 (x86,x64,ARM,ARM64,PPC,PPC64,MIPS)/plugins\HexRaysPyTools\core\cache.py", line 70, in initialize_cache
    _init_demangled_names()
  File "D:\IDA Pro 7.6.210427 (x86,x64,ARM,ARM64,PPC,PPC64,MIPS)/plugins\HexRaysPyTools\core\cache.py", line 56, in _init_demangled_names
    short_name = common.demangled_name_to_c_str(short_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IDA Pro 7.6.210427 (x86,x64,ARM,ARM64,PPC,PPC64,MIPS)/plugins\HexRaysPyTools\core\common.py", line 106, in demangled_name_to_c_str
    raise AssertionError("Replacement of demangled string by c-string for keyword `operatorXXX` is not yet"
AssertionError: Replacement of demangled string by c-string for keyword `operatorXXX` is not yetimplemented (class CryTransform::CAngle CryTransform::operator"" _radians(unsigned __int64)). You can do it by yourself or create an issue```

**Comment by komimoe** [comment]
plugin works well just replace ```elif name[idx:idx + 2] == "\"\" ":``` with ```elif name[idx:idx + 3] == "\"\" ":``` in common.py line 99.
