### ISSUE TITLE
IDA 7.0   Cann't normal use

### ISSUE THREAD

**Issue by ydc1992** [igogo-x86/HexRaysPyTools#9]
output as below,SDK maybe modify, ctx is don't have form_title

Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 608, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 1063, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 1106, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 507, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 928, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 928, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 1141, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 422, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 368, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 312, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 261, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 1015, in update
    if ctx.form_title[0:10] == "Pseudocode":
AttributeError: 'action_update_ctx_t' object has no attribute 'form_title'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\HexRaysPyTools\Actions.py", line 461, in update
    idaapi.attach_action_to_popup(ctx.form, None, self.name)
AttributeError: 'action_update_ctx_t' object has no attribute 'form'

**Comment by igogo-x86** [comment]
Hello! Unfortunately, I havn't seen new version of IDA yet

**Comment by ydc1992** [comment]
There is leak IDA,https://mega.nz/#F!1hwHCRAQ!1FVT5NtXrnKTOdG-soDrRg

**Comment by ydc1992** [comment]
Hi , I find the change for IDA 7.0 API.

```
if ctx.form.type==ida.BWN_PSEUDOCODE:
```
and 
```
idaapi.attach_action_to_pop(cxt.widget,None,self.name)
```

**Comment by rigmar** [comment]
Here is my fork with IDA 7.0 support. It was not tested enough and has differences from the original.
[https://github.com/rigmar/HexRaysPyTools)](https://github.com/rigmar/HexRaysPyTools)

**Comment by igogo-x86** [comment]
Now, it works for IDA 7.0 (and doesn't work for lower versions)
